steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/image-gallery', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/image-gallery']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: [ '-c', 'gcloud secrets versions access latest --secret=gallery-apikey > decrypted.txt' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'image-gallery'
  - '--image'
  - 'gcr.io/$PROJECT_ID/image-gallery'
  - '--region'
  - 'us-east1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--max-instances'
  - '2'
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: [ '-c', 'gcloud run services update image-gallery --platform managed --region us-east1 --set-env-vars=API_KEY=$(cat decrypted.txt)' ]
images:
- 'gcr.io/$PROJECT_ID/image-gallery'
    
